GET http://127.0.0.1:8000/cats/

###

GET http://127.0.0.1:8000/cats/1/

###

GET http://127.0.0.1:8000/owners/

###

POST http://127.0.0.1:8000/owners/
Content-Type: application/json

{
    "first_name": "Theodor",
    "last_name": "Voland"
}

###

POST http://127.0.0.1:8000/cats/
Content-Type: application/json

{
    "name": "Bars",
    "color": "#228B22",
    "birth_year": 2019,
    "owner": 1,
    "achievements": [
        {"achievement_name": "Broke a vase"}
    ]
}

###

DELETE http://127.0.0.1:8000/cats/4/
Content-Type: application/json

{
  }

###

PATCH  http://127.0.0.1:8000/cats/3/
Content-Type: application/json

{
    "achievements": [
        {"achievement_name": "Broke a vase"}
    ]
}