# Generated by Django 5.1.1 on 2025-03-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_achievement_achievementcat'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='achievements',
            field=models.ManyToManyField(through='cats.AchievementCat', to='cats.achievement'),
        ),
    ]
